// AUTOGENERATED By makeswamp.py - DO NOT EDIT.

package org.fenfire.swamp;
import java.util.Iterator;
import org.nongnu.navidoc.util.Obs;

/** A non-modifiable RDF graph. The iterators may implement the method
 *  remove, but it should not be used, as it may cause unspecified behavior.
 */
public interface ConstGraph {
    /** Get a ConstGraph whose queries will return the same
     * value as the queries for this graph, but will 
     * set up the Obs for those queries.
     * When the result of any of those queries changes,
     * Obs is called immediately.
     */
    ConstGraph getObservedConstGraph(org.nongnu.navidoc.util.Obs o);

    /** This observed graph will not be used any more, and
     * if desired, may be recycled.
     * This operation is allowed to be a no-op, and
     * if the graph this method is called on is not one that
     * has been returned by getObservedConstGraph, is
     * defined to be so..
     */
    void close();

    /** If this graph is observed (returned from getObservedConstGraph),
     * get the observer.
     */
    Obs getObserver();
    /** If this graph is observed (returned from getObservedConstGraph),
     * get the original.
     */
    ConstGraph getOriginalConstGraph();

    boolean contains(Object e0, Object e1, Object e2);
    boolean contains(Object e0, Object e1, Object e2, Obs o);

    Object find1_11X(Object e0,Object e1) ;
Object find1_1X1(Object e0,Object e2) ;
Object find1_X11(Object e1,Object e2) ;
Object find1_1XA(Object e0) ;
Object find1_XAA() ;
Object find1_X1A(Object e1) ;
Iterator findN_11X_Iter(Object e0,Object e1) ;
Iterator findN_1X1_Iter(Object e0,Object e2) ;
Iterator findN_X11_Iter(Object e1,Object e2) ;
Iterator findN_1XA_Iter(Object e0) ;
Iterator findN_XAA_Iter() ;
Iterator findN_X1A_Iter(Object e1) ;

    Object find1_11X(Object e0,Object e1,Obs obs) ;
Object find1_1X1(Object e0,Object e2,Obs obs) ;
Object find1_X11(Object e1,Object e2,Obs obs) ;
Object find1_1XA(Object e0,Obs obs) ;
Object find1_XAA(Obs obs) ;
Object find1_X1A(Object e1,Obs obs) ;
Iterator findN_11X_Iter(Object e0,Object e1,Obs obs) ;
Iterator findN_1X1_Iter(Object e0,Object e2,Obs obs) ;
Iterator findN_X11_Iter(Object e1,Object e2,Obs obs) ;
Iterator findN_1XA_Iter(Object e0,Obs obs) ;
Iterator findN_XAA_Iter(Obs obs) ;
Iterator findN_X1A_Iter(Object e1,Obs obs) ;


}

