// AUTOGENERATED By makeswamp.py - DO NOT EDIT.

package org.fenfire.swamp;
import java.util.Iterator;
import org.nongnu.navidoc.util.Obs;

/** A modifiable RDF graph. Existing iterators should not be used after
 *  the graph is modified, as it may cause unspecified behavior.
 */
public interface Graph extends ConstGraph {
    Graph getObservedGraph(org.nongnu.navidoc.util.Obs o);
    void set1_11X(Object subject, Object predicate, Object object);

    void rm_111(Object e0,Object e1,Object e2) ;
void rm_11A(Object e0,Object e1) ;
void rm_A11(Object e1,Object e2) ;
void rm_1AA(Object e0) ;


    void add(Object subject, Object predicate, Object object);

    void addAll(Graph g);
}

