// AUTOGENERATED By makeswamp2.py - DO NOT EDIT.

package org.fenfire.swamp;
import java.util.Iterator;
import org.nongnu.navidoc.util.Obs;

/** A modifiable RDF graph. Existing iterators should not be used after
 *  the graph is modified, as it may cause unspecified behavior.
 */
public interface QuadsGraph extends QuadsConstGraph {
    QuadsGraph getObservedGraph(org.nongnu.navidoc.util.Obs o);

    void set1_11XA(Object subject, Object predicate, Object object);
    void add(Object subject, Object predicate, Object object, Object context);

    void rm_1111(Object subj, Object pred, Object obj, Object context);
void rm_11AA(Object subj, Object pred);
void rm_AAA1(Object context);
void rm_111A(Object subj, Object pred, Object obj);

}
