// AUTOGENERATED By makeswamp.py - DO NOT EDIT.

package org.fenfire.swamp;
import java.util.Iterator;
import org.nongnu.navidoc.util.Obs;

/** A modifiable RDF graph. Existing iterators should not be used after
 *  the graph is modified, as it may cause unspecified behavior.
 */
public interface QuadsGraph extends QuadsConstGraph {
    QuadsGraph getObservedGraph(org.nongnu.navidoc.util.Obs o);
    void set1_11XA(Object subject, Object predicate, Object object);

    void rm_1111(Object e0,Object e1,Object e2,Object e3);
    void rm_11AA(Object e0,Object e1);
    void rm_AAA1(Object e3);
    

    void add(Object subject, Object predicate, Object object, Object quart) ;
}

