// AUTOGENERATED By makeswamp.py - DO NOT EDIT.

package org.fenfire.swamp.impl;
import org.nongnu.navidoc.util.Obs;
import org.fenfire.swamp.*;
import java.util.Iterator;

abstract public class AbstractQuadsConstGraph implements QuadsConstGraph {

    public QuadsConstGraph getObservedConstGraph(Obs obs) {
	return new StdObservedQuadsConstGraph(this, obs);
    }
    public void close() { }
    public Obs getObserver() { return null; }
    public QuadsConstGraph getOriginalConstGraph() { return null; }
    public boolean contains(Object e0, Object e1, Object e2, Object e3) {
	return contains(e0, e1, e2, e3, null);
    }

    public Object find1_111X(Object e0,Object e1,Object e2){
	 return  this.find1_111X(e0,e1,e2,null);
    }
    public Object find1_11X1(Object e0,Object e1,Object e3){
	 return  this.find1_11X1(e0,e1,e3,null);
    }
    public Object find1_1X11(Object e0,Object e2,Object e3){
	 return  this.find1_1X11(e0,e2,e3,null);
    }
    public Object find1_X111(Object e1,Object e2,Object e3){
	 return  this.find1_X111(e1,e2,e3,null);
    }
    public Object find1_11XA(Object e0,Object e1){
	 return  this.find1_11XA(e0,e1,null);
    }
    public Object find1_1X1A(Object e0,Object e2){
	 return  this.find1_1X1A(e0,e2,null);
    }
    public Object find1_X11A(Object e1,Object e2){
	 return  this.find1_X11A(e1,e2,null);
    }
    public Object find1_11AX(Object e0,Object e1){
	 return  this.find1_11AX(e0,e1,null);
    }
    public Object find1_1XAA(Object e0){
	 return  this.find1_1XAA(e0,null);
    }
    public Object find1_1XA1(Object e0,Object e3){
	 return  this.find1_1XA1(e0,e3,null);
    }
    public Object find1_XAAA(){
	 return  this.find1_XAAA(null);
    }
    public Object find1_XAA1(Object e3){
	 return  this.find1_XAA1(e3,null);
    }
    public Object find1_X1AA(Object e1){
	 return  this.find1_X1AA(e1,null);
    }
    public Object find1_X1A1(Object e1,Object e3){
	 return  this.find1_X1A1(e1,e3,null);
    }
    public Iterator findN_111X_Iter(Object e0,Object e1,Object e2){
	 return  this.findN_111X_Iter(e0,e1,e2,null);
    }
    public Iterator findN_11X1_Iter(Object e0,Object e1,Object e3){
	 return  this.findN_11X1_Iter(e0,e1,e3,null);
    }
    public Iterator findN_1X11_Iter(Object e0,Object e2,Object e3){
	 return  this.findN_1X11_Iter(e0,e2,e3,null);
    }
    public Iterator findN_X111_Iter(Object e1,Object e2,Object e3){
	 return  this.findN_X111_Iter(e1,e2,e3,null);
    }
    public Iterator findN_11XA_Iter(Object e0,Object e1){
	 return  this.findN_11XA_Iter(e0,e1,null);
    }
    public Iterator findN_1X1A_Iter(Object e0,Object e2){
	 return  this.findN_1X1A_Iter(e0,e2,null);
    }
    public Iterator findN_X11A_Iter(Object e1,Object e2){
	 return  this.findN_X11A_Iter(e1,e2,null);
    }
    public Iterator findN_11AX_Iter(Object e0,Object e1){
	 return  this.findN_11AX_Iter(e0,e1,null);
    }
    public Iterator findN_1XAA_Iter(Object e0){
	 return  this.findN_1XAA_Iter(e0,null);
    }
    public Iterator findN_1XA1_Iter(Object e0,Object e3){
	 return  this.findN_1XA1_Iter(e0,e3,null);
    }
    public Iterator findN_XAAA_Iter(){
	 return  this.findN_XAAA_Iter(null);
    }
    public Iterator findN_XAA1_Iter(Object e3){
	 return  this.findN_XAA1_Iter(e3,null);
    }
    public Iterator findN_X1AA_Iter(Object e1){
	 return  this.findN_X1AA_Iter(e1,null);
    }
    public Iterator findN_X1A1_Iter(Object e1,Object e3){
	 return  this.findN_X1A1_Iter(e1,e3,null);
    }
    

}
