// AUTOGENERATED By makeswamp.py - DO NOT EDIT.

package org.fenfire.swamp.impl;
import org.nongnu.navidoc.util.Obs;
import org.fenfire.swamp.*;
import java.util.Iterator;

abstract public class AbstractConstGraph implements ConstGraph {

    public ConstGraph getObservedConstGraph(Obs obs) {
	return new StdObservedConstGraph(this, obs);
    }
    public void close() { }
    public Obs getObserver() { return null; }
    public ConstGraph getOriginalConstGraph() { return null; }
    public boolean contains(Object e0, Object e1, Object e2) {
	return contains(e0, e1, e2, null);
    }

    public Object find1_11X(Object e0,Object e1) {
	 return  this.find1_11X(e0,e1,null);
}
public Object find1_1X1(Object e0,Object e2) {
	 return  this.find1_1X1(e0,e2,null);
}
public Object find1_X11(Object e1,Object e2) {
	 return  this.find1_X11(e1,e2,null);
}
public Object find1_1XA(Object e0) {
	 return  this.find1_1XA(e0,null);
}
public Object find1_XAA() {
	 return  this.find1_XAA(null);
}
public Object find1_X1A(Object e1) {
	 return  this.find1_X1A(e1,null);
}
public Iterator findN_11X_Iter(Object e0,Object e1) {
	 return  this.findN_11X_Iter(e0,e1,null);
}
public Iterator findN_1X1_Iter(Object e0,Object e2) {
	 return  this.findN_1X1_Iter(e0,e2,null);
}
public Iterator findN_X11_Iter(Object e1,Object e2) {
	 return  this.findN_X11_Iter(e1,e2,null);
}
public Iterator findN_1XA_Iter(Object e0) {
	 return  this.findN_1XA_Iter(e0,null);
}
public Iterator findN_XAA_Iter() {
	 return  this.findN_XAA_Iter(null);
}
public Iterator findN_X1A_Iter(Object e1) {
	 return  this.findN_X1A_Iter(e1,null);
}


}
