// AUTOGENERATED By makeswamp.py - DO NOT EDIT.

package org.fenfire.swamp.impl;
import org.nongnu.navidoc.util.Obs;
import org.fenfire.swamp.*;
import java.util.Iterator;

abstract public class AbstractConstGraph implements ConstGraph {

    public ConstGraph getObservedConstGraph(Obs obs) {
	return new StdObservedConstGraph(this, obs);
    }
    public void close() { }
    public Obs getObserver() { return null; }
    public ConstGraph getOriginalConstGraph() { return null; }
    public boolean contains(Object e0, Object e1, Object e2) {
	return contains(e0, e1, e2, null);
    }

    public Object find1_11X(Object subj, Object pred) {
    return find1_11X(subj, pred, null);
}
public Iterator findN_11X_Iter(Object subj, Object pred) {
    return findN_11X_Iter(subj, pred, null);
}
public Object find1_1X1(Object subj, Object obj) {
    return find1_1X1(subj, obj, null);
}
public Iterator findN_1X1_Iter(Object subj, Object obj) {
    return findN_1X1_Iter(subj, obj, null);
}
public Object find1_X11(Object pred, Object obj) {
    return find1_X11(pred, obj, null);
}
public Iterator findN_X11_Iter(Object pred, Object obj) {
    return findN_X11_Iter(pred, obj, null);
}
public Object find1_1XA(Object subj) {
    return find1_1XA(subj, null);
}
public Iterator findN_1XA_Iter(Object subj) {
    return findN_1XA_Iter(subj, null);
}
public Object find1_XAA() {
    return find1_XAA(null);
}
public Iterator findN_XAA_Iter() {
    return findN_XAA_Iter(null);
}
public Object find1_X1A(Object pred) {
    return find1_X1A(pred, null);
}
public Iterator findN_X1A_Iter(Object pred) {
    return findN_X1A_Iter(pred, null);
}

}
