// AUTOGENERATED By makeswamp.py - DO NOT EDIT.

package org.fenfire.swamp.impl;
import org.nongnu.navidoc.util.Obs;
import org.fenfire.swamp.*;
import java.util.Iterator;

public abstract class DelegateGraph extends AbstractGraph {
    Graph graph;

    public DelegateGraph(Graph graph) {
	this.graph = graph;
    }
    
    public void close() { graph.close(); }
    public Obs getObserver() { return graph.getObserver(); }
    public ConstGraph getOriginalConstGraph() {
        return graph.getOriginalConstGraph();    }
    public ConstGraph getObservedConstGraph(Obs o) {
        return graph.getObservedConstGraph(o);    }
    public boolean contains(Object e0, Object e1, Object e2) {
        return graph.contains(e0,e1,e2); }
    public boolean contains(Object e0, Object e1, Object e2, Obs o) {
        return graph.contains(e0,e1,e2, o); }
    public Graph getObservedGraph(org.nongnu.navidoc.util.Obs o) {
        return graph.getObservedGraph(o); }
    public void set1_11X(Object subject, Object predicate, Object object) {
        graph.set1_11X(subject, predicate, object);   }
    public void add(Object subject, Object predicate, Object object) {
        graph.add(subject, predicate, object);     }
    public void addAll(Graph g) {
        graph.addAll(g);     }
    public void rm_111(Object subject, Object predicate, Object object) {
        graph.rm_111(subject, predicate, object);     }


    public Object find1_X11(Object pred, Object obj, Obs obs) {
    return graph.find1_X11(pred, obj, obs);
}
public Iterator findN_X11_Iter(Object pred, Object obj, Obs obs) {
    return graph.findN_X11_Iter(pred, obj, obs);
}
public Object find1_1X1(Object subj, Object obj, Obs obs) {
    return graph.find1_1X1(subj, obj, obs);
}
public Iterator findN_1X1_Iter(Object subj, Object obj, Obs obs) {
    return graph.findN_1X1_Iter(subj, obj, obs);
}
public Object find1_11X(Object subj, Object pred, Obs obs) {
    return graph.find1_11X(subj, pred, obs);
}
public Iterator findN_11X_Iter(Object subj, Object pred, Obs obs) {
    return graph.findN_11X_Iter(subj, pred, obs);
}
public Object find1_X1A(Object pred, Obs obs) {
    return graph.find1_X1A(pred, obs);
}
public Iterator findN_X1A_Iter(Object pred, Obs obs) {
    return graph.findN_X1A_Iter(pred, obs);
}
public Object find1_1XA(Object subj, Obs obs) {
    return graph.find1_1XA(subj, obs);
}
public Iterator findN_1XA_Iter(Object subj, Obs obs) {
    return graph.findN_1XA_Iter(subj, obs);
}
public Object find1_1AX(Object subj, Obs obs) {
    return graph.find1_1AX(subj, obs);
}
public Iterator findN_1AX_Iter(Object subj, Obs obs) {
    return graph.findN_1AX_Iter(subj, obs);
}
public Object find1_XA1(Object obj, Obs obs) {
    return graph.find1_XA1(obj, obs);
}
public Iterator findN_XA1_Iter(Object obj, Obs obs) {
    return graph.findN_XA1_Iter(obj, obs);
}
public Object find1_AX1(Object obj, Obs obs) {
    return graph.find1_AX1(obj, obs);
}
public Iterator findN_AX1_Iter(Object obj, Obs obs) {
    return graph.findN_AX1_Iter(obj, obs);
}
public Object find1_A1X(Object pred, Obs obs) {
    return graph.find1_A1X(pred, obs);
}
public Iterator findN_A1X_Iter(Object pred, Obs obs) {
    return graph.findN_A1X_Iter(pred, obs);
}
public Object find1_XAA(Obs obs) {
    return graph.find1_XAA(obs);
}
public Iterator findN_XAA_Iter(Obs obs) {
    return graph.findN_XAA_Iter(obs);
}
public Object find1_AXA(Obs obs) {
    return graph.find1_AXA(obs);
}
public Iterator findN_AXA_Iter(Obs obs) {
    return graph.findN_AXA_Iter(obs);
}
public Object find1_AAX(Obs obs) {
    return graph.find1_AAX(obs);
}
public Iterator findN_AAX_Iter(Obs obs) {
    return graph.findN_AAX_Iter(obs);
}

}
