// AUTOGENERATED By makeswamp2.py - DO NOT EDIT.

package org.fenfire.swamp.impl;
import org.nongnu.navidoc.util.Obs;
import org.fenfire.swamp.*;
import java.util.Iterator;

public class OneQuadGraph extends AbstractGraph {
    protected QuadsGraph graph;
    protected Object context;

    public OneQuadGraph(QuadsGraph graph, Object context) {
	this.graph = graph;
        this.context = context;
    }

    public Obs getObserver() { return graph.getObserver(); }
    public boolean contains(Object subj, Object pred, Object obj) {
        return graph.contains(subj,pred,obj, context); }
    public boolean contains(Object subj, Object pred, Object obj, Obs o) {
        return graph.contains(subj,pred,obj, context, o); }
    public void add(Object subject, Object predicate, Object object) {
        graph.add(subject, predicate, object, context);     }

    public Object find1_11X(Object subj, Object pred, Obs obs) {
    return graph.find1_11X1(subj, pred, context, obs);
}
public Iterator findN_11X_Iter(Object subj, Object pred, Obs obs){
    return graph.findN_11X1_Iter(subj, pred, context, obs);
}
public Object find1_1X1(Object subj, Object obj, Obs obs) {
    return graph.find1_1X11(subj, obj, context, obs);
}
public Iterator findN_1X1_Iter(Object subj, Object obj, Obs obs){
    return graph.findN_1X11_Iter(subj, obj, context, obs);
}
public Object find1_X11(Object pred, Object obj, Obs obs) {
    return graph.find1_X111(pred, obj, context, obs);
}
public Iterator findN_X11_Iter(Object pred, Object obj, Obs obs){
    return graph.findN_X111_Iter(pred, obj, context, obs);
}
public Object find1_1XA(Object subj, Obs obs) {
    return graph.find1_1XA1(subj, context, obs);
}
public Iterator findN_1XA_Iter(Object subj, Obs obs){
    return graph.findN_1XA1_Iter(subj, context, obs);
}
public Object find1_XAA(Obs obs) {
    return graph.find1_XAA1(context, obs);
}
public Iterator findN_XAA_Iter(Obs obs){
    return graph.findN_XAA1_Iter(context, obs);
}
public Object find1_X1A(Object pred, Obs obs) {
    return graph.find1_X1A1(pred, context, obs);
}
public Iterator findN_X1A_Iter(Object pred, Obs obs){
    return graph.findN_X1A1_Iter(pred, context, obs);
}
public void rm_111(Object subject, Object predicate, 
                   Object object) {
graph.rm_1111(subject, predicate, object, context);
}

}
