// AUTOGENERATED By makeswamp.py - DO NOT EDIT.

package org.fenfire.swamp.impl;
import org.nongnu.navidoc.util.Obs;
import org.fenfire.swamp.*;
import java.util.Iterator;

public class StdObservedQuadsGraph extends StdObservedQuadsConstGraph
         implements QuadsGraph {
    QuadsGraph graph;

    public StdObservedQuadsGraph(QuadsGraph graph, Obs obs) {
	super(graph, obs);
	this.graph = graph;
	this.obs = obs;
    }

    public QuadsGraph getObservedGraph(Obs obs) {
	throw new Error("DoubleObs");
    }

    public void rm_111A(Object subj, Object pred, Object obj) {
    graph.rm_111A(subj, pred, obj);
}
public void rm_11AA(Object subj, Object pred) {
    graph.rm_11AA(subj, pred);
}
public void rm_A11A(Object pred, Object obj) {
    graph.rm_A11A(pred, obj);
}
public void rm_1AAA(Object subj) {
    graph.rm_1AAA(subj);
}
public void rm_1111(Object subj, Object pred, Object obj, Object context) {
    graph.rm_1111(subj, pred, obj, context);
}
public void rm_11A1(Object subj, Object pred, Object context) {
    graph.rm_11A1(subj, pred, context);
}
public void rm_A111(Object pred, Object obj, Object context) {
    graph.rm_A111(pred, obj, context);
}
public void rm_1AA1(Object subj, Object context) {
    graph.rm_1AA1(subj, context);
}
public void rm_AAA1(Object context) {
    graph.rm_AAA1(context);
}


    public void add(Object subject, Object predicate, Object object, Object quad) {
	graph.add(subject, predicate, object, quad);
    }
}
