// AUTOGENERATED By makeswamp.py - DO NOT EDIT.

package org.fenfire.swamp.impl;
import org.nongnu.navidoc.util.Obs;
import org.fenfire.swamp.*;
import java.util.Iterator;

public class StdObservedQuadsGraph extends StdObservedQuadsConstGraph
         implements QuadsGraph {
    QuadsGraph graph;

    public StdObservedQuadsGraph(QuadsGraph graph, Obs obs) {
	super(graph, obs);
	this.graph = graph;
	this.obs = obs;
    }

    public QuadsGraph getObservedGraph(Obs obs) {
	throw new Error("DoubleObs");
    }

    public void set1_11XA(Object subject, Object predicate, Object object) {
    	graph.set1_11XA(subject, predicate, object);
    }

    public void rm_1111(Object e0,Object e1,Object e2,Object e3){
	  graph.rm_1111(e0,e1,e2,e3);
    }
    public void rm_11AA(Object e0,Object e1){
	  graph.rm_11AA(e0,e1);
    }
    public void rm_AAA1(Object e3){
	  graph.rm_AAA1(e3);
    }
    public void rm_111A(Object e0,Object e1,Object e2){
	  graph.rm_111A(e0,e1,e2);
    }
    

    public void add(Object subject, Object predicate, Object object, Object quad) {
	graph.add(subject, predicate, object, quad);
    }
}

