// AUTOGENERATED By makeswamp2.py - DO NOT EDIT.

package org.fenfire.swamp.impl;
import org.nongnu.navidoc.util.Obs;
import org.fenfire.swamp.*;
import java.util.Iterator;

public class StdObservedQuadsGraph extends StdObservedQuadsConstGraph
         implements QuadsGraph {
    QuadsGraph graph;

    public StdObservedQuadsGraph(QuadsGraph graph, Obs obs) {
	super(graph, obs);
	this.graph = graph;
	this.obs = obs;
    }

    public QuadsGraph getObservedGraph(Obs obs) {
	throw new Error("DoubleObs");
    }

    public void set1_11XA(Object subject, Object predicate, Object object) {
    	graph.set1_11XA(subject, predicate, object);
    }

    public void rm_1111(Object subj, Object pred, Object obj, Object context) {
    graph.rm_1111(subj, pred, obj, context);
}
public void rm_11AA(Object subj, Object pred) {
    graph.rm_11AA(subj, pred);
}
public void rm_AAA1(Object context) {
    graph.rm_AAA1(context);
}
public void rm_111A(Object subj, Object pred, Object obj) {
    graph.rm_111A(subj, pred, obj);
}


    public void add(Object subject, Object predicate, Object object, Object quad) {
	graph.add(subject, predicate, object, quad);
    }
}
